<?php

namespace AppBundle\Repository;

/**
 * InterestPointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestPointsRepository extends \Doctrine\ORM\EntityRepository
{
}
